/**
 * Mock Case Dossier fixtures.
 */
import { Case } from '@/types/case';

export const MOCK_CASES: readonly Case[] = [
  // Hero Case
  {
    id: 'CASE-2024-0042',
    title: 'Multi-Entity Pain & Toxicology Network (Mercer)',
    focal_provider_id: 'P0042',
    focal_provider_name: 'Dr. Victor Mercer, MD',
    specialty: 'pain_management',
    status: 'open',
    priority_score: 96,
    risk_index: 94,
    confidence: 'High',
    severity: 'CRITICAL',
    est_dollars: 412000.0,
    est_overpay: 126695.5,
    rules_triggered: ['R06', 'R07', 'R08', 'R09', 'R10'],
    primary_indicator:
      'Indicators consistent with 6-entity shared banking ring, reciprocal PT referrals, and same-day toxicology panel surge',
    created_at: '2024-09-15T08:30:00Z',
    updated_at: '2024-09-18T14:20:00Z',
    sla_due_date: '2024-09-25T17:00:00Z',
    assigned_investigator: null,
    conflicting_signals: [
      {
        title: 'Patient Satisfaction vs Service Volume',
        positive_indicator: 'Low formal patient grievance rate (0.12 per 1,000 panel members)',
        risk_indicator: '18.7 daily billing hours with 78.4 mph travel requirement between consecutive clinics',
        explanation:
          'High patient volume and lack of direct member complaints may indicate satisfied patient throughput, but impossible physical timing suggests subordinate personnel billing without supervision modifiers.',
      },
      {
        title: 'Credentialing Standing vs Entity Clustering',
        positive_indicator: 'Clean state medical board license with no prior administrative sanctions',
        risk_indicator: 'Exact shared bank account routing number linking 4 distinct clinic entities',
        explanation:
          'Individual credentialing profiles appear compliant, but backend financial concentration reflects concealed unified management and cross-referral steering.',
      },
    ],
    evidence_count: 8,
    claim_count: 8,
    network_id: 'NET-RING-001',
    decision: null,
  },
  {
    id: 'CASE-2024-0088',
    title: 'Concurrent Multi-Site Surgical Procedures (Chen)',
    focal_provider_id: 'P0088',
    focal_provider_name: 'Dr. Sarah Chen, MD',
    specialty: 'dermatology',
    status: 'open',
    priority_score: 86,
    risk_index: 84,
    confidence: 'High',
    severity: 'HIGH',
    est_dollars: 185000.0,
    est_overpay: 42000.0,
    rules_triggered: ['R06', 'R08'],
    primary_indicator:
      'Pattern similarity indicating simultaneous procedural billing across distant facility locations',
    created_at: '2024-09-16T10:15:00Z',
    updated_at: '2024-09-18T11:00:00Z',
    sla_due_date: '2024-09-28T17:00:00Z',
    assigned_investigator: 'SIU Officer #108',
    conflicting_signals: [
      {
        title: 'Teaching Hospital Affiliation vs Overlap',
        positive_indicator: 'Documented clinical teaching faculty status at affiliated medical center',
        risk_indicator: 'Concurrent procedural start times without teaching physician modifier (GC/GE)',
        explanation:
          'Teaching facility setting often involves resident cases, but absence of required modifier causes overlap flag.',
      },
    ],
    evidence_count: 3,
    claim_count: 14,
    network_id: null,
    decision: null,
  },
  {
    id: 'CASE-2024-0115',
    title: 'Level 5 E&M Rapid Billing Surge (House)',
    focal_provider_id: 'P0115',
    focal_provider_name: 'Dr. Gregory House, MD',
    specialty: 'internal_medicine',
    status: 'under_investigation',
    priority_score: 78,
    risk_index: 76,
    confidence: 'Medium',
    severity: 'HIGH',
    est_dollars: 145000.0,
    est_overpay: 38500.0,
    rules_triggered: ['R10'],
    primary_indicator:
      'Sudden shift to 64% Level 5 complex visit billing vs specialty peer median of 12%',
    created_at: '2024-09-14T09:00:00Z',
    updated_at: '2024-09-17T16:45:00Z',
    sla_due_date: '2024-10-02T17:00:00Z',
    assigned_investigator: 'SIU Officer #104',
    conflicting_signals: [],
    evidence_count: 2,
    claim_count: 22,
    network_id: null,
    decision: null,
  },
  {
    id: 'CASE-2024-0192',
    title: 'High-Concentration Diagnostic Imaging Loop (Webster)',
    focal_provider_id: 'P0045',
    focal_provider_name: 'Dr. Diana Croft, MD',
    specialty: 'radiology',
    status: 'open',
    priority_score: 74,
    risk_index: 72,
    confidence: 'Medium',
    severity: 'MEDIUM',
    est_dollars: 112000.0,
    est_overpay: 28400.0,
    rules_triggered: ['R07', 'R09'],
    primary_indicator:
      '89% referral capture rate from affiliated orthopedic practices under common management',
    created_at: '2024-09-13T14:30:00Z',
    updated_at: '2024-09-16T09:10:00Z',
    sla_due_date: '2024-10-05T17:00:00Z',
    assigned_investigator: null,
    conflicting_signals: [],
    evidence_count: 2,
    claim_count: 18,
    network_id: 'NET-RING-001',
    decision: null,
  },
  {
    id: 'CASE-2024-0230',
    title: 'Dispersed Rural Patient Catchment Anomaly (Thorne)',
    focal_provider_id: 'P0044',
    focal_provider_name: 'Dr. Arthur Sterling, DC',
    specialty: 'chiropractic',
    status: 'open',
    priority_score: 69,
    risk_index: 68,
    confidence: 'Medium',
    severity: 'MEDIUM',
    est_dollars: 78000.0,
    est_overpay: 19500.0,
    rules_triggered: ['R08'],
    primary_indicator:
      'Over 40% of patient panel traveling >120 miles for weekly routine maintenance therapy',
    created_at: '2024-09-12T11:00:00Z',
    updated_at: '2024-09-15T13:00:00Z',
    sla_due_date: '2024-10-10T17:00:00Z',
    assigned_investigator: null,
    conflicting_signals: [],
    evidence_count: 2,
    claim_count: 16,
    network_id: null,
    decision: null,
  },
];
