/**
 * Mock Network Graph fixtures.
 * Matches network/subgraph.py and Cytoscape.js requirements.
 */
import { Network } from '@/types/network';

export const MOCK_NETWORKS: readonly Network[] = [
  {
    network_id: 'NET-RING-001',
    focal_entity: 'P0042',
    description: 'Coordinated 6-Provider Network with Shared Banking & Reciprocal Referrals',
    nodes: [
      {
        id: 'P0042',
        node_type: 'provider',
        label: 'Dr. Victor Mercer',
        name: 'Dr. Victor Mercer, MD',
        specialty: 'pain_management',
        facility_type: 'clinic',
        risk_index: 94,
        is_focal: true,
        community_id: 1,
      },
      {
        id: 'P0043',
        node_type: 'provider',
        label: 'Dr. Elena Vance',
        name: 'Dr. Elena Vance, DPT',
        specialty: 'physical_therapy',
        facility_type: 'clinic',
        risk_index: 88,
        is_focal: false,
        community_id: 1,
      },
      {
        id: 'P0044',
        node_type: 'provider',
        label: 'Dr. Arthur Sterling',
        name: 'Dr. Arthur Sterling, DC',
        specialty: 'chiropractic',
        facility_type: 'clinic',
        risk_index: 82,
        is_focal: false,
        community_id: 1,
      },
      {
        id: 'P0045',
        node_type: 'provider',
        label: 'Dr. Diana Croft',
        name: 'Dr. Diana Croft, MD',
        specialty: 'radiology',
        facility_type: 'imaging_center',
        risk_index: 79,
        is_focal: false,
        community_id: 1,
      },
      {
        id: 'P0046',
        node_type: 'provider',
        label: 'BioMatrix Labs',
        name: 'BioMatrix Toxicology Labs',
        specialty: 'laboratory',
        facility_type: 'lab',
        risk_index: 91,
        is_focal: false,
        community_id: 1,
      },
      {
        id: 'P0047',
        node_type: 'facility',
        label: 'Apex Rehab Clinic',
        name: 'Apex Physical Medicine & Rehab',
        specialty: 'physical_therapy',
        facility_type: 'clinic',
        risk_index: 85,
        is_focal: false,
        community_id: 1,
      },
      {
        id: 'BANK_HASH_01',
        node_type: 'bank_account',
        label: 'Bank Acct (...3a21)',
        name: 'Shared Bank Hash: 9a8b7c6d5e4f3a21',
        community_id: 1,
      },
      {
        id: 'OWNER_HOLDINGS',
        node_type: 'owner',
        label: 'Apex Healthcare Holdings',
        name: 'Apex Healthcare Holdings LLC',
        community_id: 1,
      },
    ],
    edges: [
      {
        source: 'P0042',
        target: 'BANK_HASH_01',
        edge_type: 'shared_bank_account',
        weight: 1.0,
        confidence: 1.0,
        matched_value: '9a8b7c6d5e4f3a21',
        evidence_ids: ['E-R09-SHARDBK-006'],
      },
      {
        source: 'P0043',
        target: 'BANK_HASH_01',
        edge_type: 'shared_bank_account',
        weight: 1.0,
        confidence: 1.0,
        matched_value: '9a8b7c6d5e4f3a21',
        evidence_ids: ['E-R09-SHARDBK-006'],
      },
      {
        source: 'P0044',
        target: 'BANK_HASH_01',
        edge_type: 'shared_bank_account',
        weight: 1.0,
        confidence: 1.0,
        matched_value: '9a8b7c6d5e4f3a21',
        evidence_ids: ['E-R09-SHARDBK-006'],
      },
      {
        source: 'P0047',
        target: 'BANK_HASH_01',
        edge_type: 'shared_bank_account',
        weight: 1.0,
        confidence: 1.0,
        matched_value: '9a8b7c6d5e4f3a21',
        evidence_ids: ['E-R09-SHARDBK-006'],
      },
      {
        source: 'P0042',
        target: 'OWNER_HOLDINGS',
        edge_type: 'shared_owner',
        weight: 0.9,
        confidence: 0.95,
        matched_value: 'Apex Healthcare Holdings LLC',
        evidence_ids: ['E-R09-SHARDON-007'],
      },
      {
        source: 'P0045',
        target: 'OWNER_HOLDINGS',
        edge_type: 'shared_owner',
        weight: 0.9,
        confidence: 0.95,
        matched_value: 'Apex Healthcare Holdings LLC',
        evidence_ids: ['E-R09-SHARDON-007'],
      },
      {
        source: 'P0046',
        target: 'OWNER_HOLDINGS',
        edge_type: 'shared_owner',
        weight: 0.9,
        confidence: 0.95,
        matched_value: 'Apex Healthcare Holdings LLC',
        evidence_ids: ['E-R09-SHARDON-007'],
      },
      {
        source: 'P0042',
        target: 'P0043',
        edge_type: 'reciprocal_referral',
        weight: 0.85,
        confidence: 0.9,
        matched_value: '82.4% Referral Concentration (n=42)',
        evidence_ids: ['E-R07-RECLOOP-003'],
      },
      {
        source: 'P0043',
        target: 'P0042',
        edge_type: 'reciprocal_referral',
        weight: 0.8,
        confidence: 0.9,
        matched_value: '38 Referrals Returned',
        evidence_ids: ['E-R07-RECLOOP-003'],
      },
      {
        source: 'P0042',
        target: 'P0046',
        edge_type: 'same_day_lab',
        weight: 0.95,
        confidence: 0.98,
        matched_value: '94.6% Same-Day Toxicology Panels',
        evidence_ids: ['E-R07-LABSAME-004'],
      },
    ],
    cohorts: [
      {
        cohort_type: 'shared_members',
        providers: ['P0042', 'P0043', 'P0046'],
        member_count: 68,
        sample_member_ids: ['M2001', 'M2002', 'M2003'],
      },
      {
        cohort_type: 'shared_members',
        providers: ['P0042', 'P0044'],
        member_count: 34,
        sample_member_ids: ['M2004', 'M2005', 'M2006'],
      },
    ],
    summary: {
      n_nodes: 8,
      n_edges: 10,
      n_cohorts: 2,
      total_members: 102,
      hub_provider_id: 'P0042',
      hard_link_score: 0.94,
      referral_loop_count: 2,
    },
  },
];
